development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: sinatrails_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: sinatrails_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: sinatrails_production
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
